import { describe, it, expect } from 'vitest'
import { formatTide, formatTideBody, buildCombined, NOAA_CREDIT, TIDE_ATTRIBUTION, COMBINED_ATTRIBUTION } from './tideFormatter'
import { formatWeather, formatWeatherBody, ATTRIBUTION } from './weatherFormatter'
import type { HourlyResponse } from './weatherFormatter'
import type { TideReading } from './tide'
import type { TideStation } from './tideStations'

const STN: TideStation = { id: '9414290', name: 'San Francisco', lat: 37.8, lng: -122.5, state: 'CA', obs: true }

const reading: TideReading = {
  levelMin: 3.2, levelMax: 4.1, source: 'observed', trend: 'rising', turnedDuring: false,
  prevHL: { kind: 'low', v: 0.6, timeLocal: '5:02am' },
  nextHL: { kind: 'high', v: 5.1, timeLocal: '11:18am' },
  station: STN, distanceMi: 3.4,
}

describe('formatTideBody', () => {
  it('renders the block ending in the bare NOAA credit (no SnowRaven)', () => {
    const b = formatTideBody(reading)
    expect(b).toContain('🌊')
    expect(b).toContain('Observed')
    expect(b).toContain('Water level: 3.2 – 4.1 ft')
    expect(b).toContain('Tide: Rising')
    expect(b).toContain('Previous low: 0.6 ft at 5:02am')
    expect(b).toContain('Next high: 5.1 ft at 11:18am')
    expect(b).toContain('Station: San Francisco (9414290), 3.4 mi away')
    expect(b).toContain('Relative to MLLW')
    expect(b.endsWith(NOAA_CREDIT)).toBe(true)
    expect(b).not.toContain('SnowRaven')
  })
  it('shows a single value when min == max', () => {
    expect(formatTideBody({ ...reading, levelMin: 3.0, levelMax: 3.0 })).toContain('Water level: 3.0 ft')
  })
  it('notes a tide that turned during the checklist', () => {
    expect(formatTideBody({ ...reading, turnedDuring: true })).toContain('Tide: Rising (turned during your checklist)')
  })
  it('labels predicted source', () => {
    expect(formatTideBody({ ...reading, source: 'predicted' })).toContain('Predicted')
  })
})

describe('formatTide (standalone)', () => {
  it('ends with the NOAA credit + SnowRaven attribution', () => {
    const s = formatTide(reading)
    expect(s.endsWith(TIDE_ATTRIBUTION)).toBe(true)
    expect(s).toContain(NOAA_CREDIT)
    expect(TIDE_ATTRIBUTION).toContain('SnowRaven')
  })
})

describe('attribution constants', () => {
  it('the combined attribution is a single SnowRaven line', () => {
    expect(COMBINED_ATTRIBUTION).toContain('Weather and tide generated by')
    expect(COMBINED_ATTRIBUTION).toContain('snowraven')
  })
})

describe('buildCombined (Copy Weather and Tide Together)', () => {
  // A real weather block (ends with the weather ATTRIBUTION line) + a real tide
  // body (ends with the bare NOAA credit), so the test is coupled to the actual
  // emitted strings.
  const hour: HourlyResponse = {
    data: [{
      dt: 1716575000, temp: 64, humidity: 72, dew_point: 55, wind_speed: 6, wind_deg: 250,
      clouds: 20, weather: [{ id: 801, description: 'few clouds' }],
      sunrise: 1716550000, sunset: 1716600000,
    }],
  }
  const weather = formatWeather([hour], 'America/Los_Angeles', 37.8)
  const tideBody = formatTideBody(reading)
  const combined = buildCombined(weather, tideBody)

  it('carries exactly one SnowRaven combined attribution and no standalone weather attribution (QA-18)', () => {
    const occurrences = (s: string, sub: string) => s.split(sub).length - 1
    expect(occurrences(combined, COMBINED_ATTRIBUTION)).toBe(1)
    // The weather block's own attribution line is stripped from the combined block.
    expect(combined).not.toContain(`\n${ATTRIBUTION}`)
    // Ends with the single combined attribution.
    expect(combined.endsWith(COMBINED_ATTRIBUTION)).toBe(true)
  })

  it('keeps the inline NOAA credit (the tide BODY, not the standalone tide block)', () => {
    expect(combined).toContain(NOAA_CREDIT)
    // The standalone tide attribution ("· via SnowRaven") never appears — the
    // combined block uses the body, which ends in the bare NOAA credit.
    expect(combined).not.toContain(TIDE_ATTRIBUTION)
  })

  it('equals SnowRaven desktop buildCombined() byte-for-byte (QA-15, .toBe parity)', () => {
    // Build `expected` from independent primitives — NOT by re-applying
    // buildCombined's own `weather.replace(...)` formula, which would be circular
    // (it would pass even if buildCombined's spacing or strip logic drifted).
    // `formatWeatherBody` is the no-attribution weather block, golden-tested
    // separately against SnowRaven; `formatWeather` is exactly that body plus
    // `\n${ATTRIBUTION}`. Asserting this precondition first makes the strip
    // meaningful, then the .toBe independently locks: weather body (attribution
    // stripped) + blank line + tide body (inline NOAA credit kept) + blank line +
    // the single combined attribution.
    const weatherBody = formatWeatherBody([hour], 'America/Los_Angeles', 37.8)
    expect(weather).toBe(`${weatherBody}\n${ATTRIBUTION}`)
    const expected = `${weatherBody}\n\n${tideBody}\n\n${COMBINED_ATTRIBUTION}`
    expect(combined).toBe(expected)
  })
})
