// Render a TideReading into the SnowRaven tide text block, mirroring the weather
// block's shape. The body and the SnowRaven attribution are separate so the
// "Copy Weather and Tide Together" action can emit ONE attribution at the bottom
// while keeping the NOAA data credit inline. See pipeline/weather-tides/design-spec.md.

import type { TideReading } from './tide'
import { ft } from './tide'
import { ATTRIBUTION } from './weatherFormatter'

// SnowRaven attribution is an HTML link (matches weatherFormatter's ATTRIBUTION),
// so it renders as a link when the block is pasted into eBird. The NOAA data
// credit stays plain text and is kept inline even in the combined copy.
const SR_LINK = '<a href="https://github.com/dtgibson/snowraven">SnowRaven</a>'
export const NOAA_CREDIT = 'Tide data from NOAA CO-OPS'
export const TIDE_ATTRIBUTION = `${NOAA_CREDIT} · via ${SR_LINK}`
export const COMBINED_ATTRIBUTION = `Weather and tide generated by ${SR_LINK}`

function levelLine(r: TideReading): string {
  const lvl = r.levelMin === r.levelMax ? `${ft(r.levelMin)} ft` : `${ft(r.levelMin)} – ${ft(r.levelMax)} ft`
  return `Water level: ${lvl}`
}

function trendLine(r: TideReading): string {
  const t = r.trend === 'rising' ? 'Rising' : 'Falling'
  return r.turnedDuring ? `Tide: ${t} (turned during your checklist)` : `Tide: ${t}`
}

/** The tide block WITHOUT the SnowRaven attribution (ends with the NOAA credit).
 *  Used by the combined copy; the standalone block appends "· via SnowRaven". */
export function formatTideBody(r: TideReading): string {
  const lines: string[] = [
    '🌊',
    r.source === 'observed' ? 'Observed' : 'Predicted',
    levelLine(r),
    trendLine(r),
  ]
  if (r.prevHL) lines.push(`Previous ${r.prevHL.kind}: ${ft(r.prevHL.v)} ft at ${r.prevHL.timeLocal}`)
  if (r.nextHL) lines.push(`Next ${r.nextHL.kind}: ${ft(r.nextHL.v)} ft at ${r.nextHL.timeLocal}`)
  lines.push(`Station: ${r.station.name} (${r.station.id}), ${r.distanceMi.toFixed(1)} mi away`)
  lines.push('Relative to MLLW')
  lines.push(NOAA_CREDIT)
  return lines.join('\n')
}

/** The standalone tide block (NOAA credit + SnowRaven attribution). */
export function formatTide(r: TideReading): string {
  // formatTideBody ends with the bare NOAA credit; the standalone block extends
  // that line to credit SnowRaven too. Plain slice (not a RegExp) — matches the
  // Python formatter and avoids treating the constant as a pattern.
  const body = formatTideBody(r)
  return body.endsWith(NOAA_CREDIT)
    ? body.slice(0, -NOAA_CREDIT.length) + TIDE_ATTRIBUTION
    : body
}

/**
 * The "Copy Weather and Tide Together" block: ONE SnowRaven attribution at the
 * very bottom. The weather block's own trailing attribution line is stripped and
 * the tide BODY (which keeps the inline NOAA credit) is appended, then a single
 * COMBINED_ATTRIBUTION. Shared by the Weather tab and the comparer's per-side
 * combined copy so both surfaces emit a byte-identical block (one attribution).
 */
export function buildCombined(weatherFormatted: string, tideBody: string): string {
  return `${weatherFormatted.replace(`\n${ATTRIBUTION}`, '')}\n\n${tideBody}\n\n${COMBINED_ATTRIBUTION}`
}
