export interface HourlyResponse {
  data: Array<{
    temp: number;
    humidity: number;
    dew_point: number;
    wind_speed: number;
    wind_deg: number;
    clouds: number;
    weather: Array<{ id: number; description: string }>;
    sunrise: number;
    sunset: number;
  }>;
}

const BEAUFORT: Array<[number, string]> = [
  [1, 'Calm'],
  [3, 'Mostly calm'],
  [7, 'Light breeze'],
  [12, 'Gentle breeze'],
  [18, 'Moderate breeze'],
  [24, 'Fresh breeze'],
  [31, 'Strong breeze'],
  [38, 'Near gale'],
  [Infinity, 'Gale'],
];

const BEAUFORT_ORDER: Record<string, number> = Object.fromEntries(
  BEAUFORT.map(([, label], i) => [label, i])
);

const CARDINALS = ['N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW'];

export const ATTRIBUTION = 'Weather generated by <a href="https://github.com/dtgibson/snowraven">SnowRaven</a>';

// Replicates Python's round() which uses round-half-to-even (banker's rounding).
// JavaScript's Math.round() uses round-half-away-from-zero and diverges at .5 boundaries.
export function bankersRound(n: number): number {
  const floor = Math.floor(n);
  const diff = n - floor;
  if (diff === 0.5) return floor % 2 === 0 ? floor : floor + 1;
  return Math.round(n);
}

export function windDescription(mph: number): string {
  for (const [threshold, label] of BEAUFORT) {
    if (mph <= threshold) return label;
  }
  return 'Gale';
}

export function cardinal(degrees: number): string {
  return CARDINALS[bankersRound(degrees / 45) % 8];
}

export function conditionEmoji(owmId: number): string {
  if (owmId >= 200 && owmId <= 232) return '⛈️';
  if (owmId >= 300 && owmId <= 321) return '🌦️';
  if (owmId >= 500 && owmId <= 531) return '🌧️';
  if (owmId >= 600 && owmId <= 622) return '❄️';
  if (owmId >= 700 && owmId <= 781) return '🌫️';
  if (owmId === 800) return '☀️';
  if (owmId === 801) return '🌤️';
  if (owmId === 802) return '⛅';
  if (owmId === 803) return '🌥️';
  if (owmId === 804) return '☁️';
  return '🌡️';
}

export function formatRange(values: number[], unit: string): string {
  const rounded = values.map(bankersRound);
  const lo = Math.min(...rounded);
  const hi = Math.max(...rounded);
  if (lo === hi) return `${lo}${unit}`;
  return `${lo} - ${hi}${unit}`;
}

export function formatLocalTime(unixTs: number, tzName: string): string {
  const date = new Date(unixTs * 1000);
  const parts = new Intl.DateTimeFormat('en-US', {
    hour: 'numeric',
    minute: '2-digit',
    hour12: true,
    timeZone: tzName,
  }).formatToParts(date);
  const hour = parts.find(p => p.type === 'hour')!.value;
  const minute = parts.find(p => p.type === 'minute')!.value;
  const dayPeriod = parts.find(p => p.type === 'dayPeriod')!.value.toLowerCase();
  return `${hour}:${minute}${dayPeriod}`;
}

function capitalize(s: string): string {
  if (!s) return s;
  const lower = s.toLowerCase();
  return lower[0].toUpperCase() + lower.slice(1);
}

// The weather block WITHOUT the SnowRaven attribution line. The standalone
// formatWeather appends ATTRIBUTION; the "Copy Weather and Tide Together" action
// uses the body so it can emit ONE combined attribution at the very bottom.
export function formatWeatherBody(responses: HourlyResponse[], tzName: string): string {
  const first = responses[0].data[0];

  const temps = responses.map(r => r.data[0].temp);
  const humids = responses.map(r => r.data[0].humidity);
  const dews = responses.map(r => r.data[0].dew_point);
  const windSpeeds = responses.map(r => r.data[0].wind_speed);

  const windDescs = [...new Set(windSpeeds.map(windDescription))].sort(
    (a, b) => BEAUFORT_ORDER[a] - BEAUFORT_ORDER[b]
  );

  const seenDirs = new Set<string>();
  const windDirs: string[] = [];
  for (const r of responses) {
    const dir = cardinal(r.data[0].wind_deg);
    if (!seenDirs.has(dir)) {
      seenDirs.add(dir);
      windDirs.push(dir);
    }
  }

  const clouds = responses.map(r => r.data[0].clouds);
  const emoji = conditionEmoji(first.weather[0].id);
  const condition = capitalize(first.weather[0].description);
  const sunrise = formatLocalTime(first.sunrise, tzName);
  const sunset = formatLocalTime(first.sunset, tzName);

  return [
    emoji,
    condition,
    `Temperature: ${formatRange(temps, '°F')}`,
    `Wind: ${windDescs.join(' - ')}`,
    `Wind Direction: ${windDirs.join(' - ')}`,
    `Cloud Cover: ${formatRange(clouds, '%')}`,
    `Humidity: ${formatRange(humids, '%')}`,
    `Dew point: ${formatRange(dews, '°F')}`,
    `Sunrise: ${sunrise}`,
    `Sunset: ${sunset}`,
  ].join('\n');
}

export function formatWeather(responses: HourlyResponse[], tzName: string): string {
  return `${formatWeatherBody(responses, tzName)}\n${ATTRIBUTION}`;
}
