export interface HourlyResponse {
  data: Array<{
    dt: number;
    temp: number;
    humidity: number;
    dew_point: number;
    wind_speed: number;
    wind_deg: number;
    clouds: number;
    weather: Array<{ id: number; description: string }>;
    sunrise: number;
    sunset: number;
  }>;
}

const BEAUFORT: Array<[number, string]> = [
  [1, 'Calm'],
  [3, 'Mostly calm'],
  [7, 'Light breeze'],
  [12, 'Gentle breeze'],
  [18, 'Moderate breeze'],
  [24, 'Fresh breeze'],
  [31, 'Strong breeze'],
  [38, 'Near gale'],
  [Infinity, 'Gale'],
];

const BEAUFORT_ORDER: Record<string, number> = Object.fromEntries(
  BEAUFORT.map(([, label], i) => [label, i])
);

const CARDINALS = ['N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW'];

export const ATTRIBUTION = 'Weather generated by <a href="https://github.com/dtgibson/snowraven">SnowRaven</a>';

// Replicates Python's round() which uses round-half-to-even (banker's rounding).
// JavaScript's Math.round() uses round-half-away-from-zero and diverges at .5 boundaries.
export function bankersRound(n: number): number {
  const floor = Math.floor(n);
  const diff = n - floor;
  if (diff === 0.5) return floor % 2 === 0 ? floor : floor + 1;
  return Math.round(n);
}

export function windDescription(mph: number): string {
  for (const [threshold, label] of BEAUFORT) {
    if (mph <= threshold) return label;
  }
  return 'Gale';
}

export function cardinal(degrees: number): string {
  return CARDINALS[bankersRound(degrees / 45) % 8];
}

export function conditionEmoji(owmId: number): string {
  if (owmId >= 200 && owmId <= 232) return '⛈️';
  if (owmId >= 300 && owmId <= 321) return '🌦️';
  if (owmId >= 500 && owmId <= 531) return '🌧️';
  if (owmId >= 600 && owmId <= 622) return '❄️';
  if (owmId >= 700 && owmId <= 781) return '🌫️';
  if (owmId === 800) return '☀️';
  if (owmId === 801) return '🌤️';
  if (owmId === 802) return '⛅';
  if (owmId === 803) return '🌥️';
  if (owmId === 804) return '☁️';
  return '🌡️';
}

// Moon phase — a port of lunarphase-js@2.0.3 (pinned from the npm dist), with one
// deliberate deviation: the Julian Day is computed in PURE UTC (the library bakes
// in the runtime's local tz offset). This MUST stay identical to SnowRaven's
// weatherFormatter.ts (and its Python oracle) so the night blocks are byte-identical.
const LUNAR_MONTH = 29.53058770576;

// Bin upper bounds (age <) at odd multiples of LUNAR_MONTH / 16; ages at or
// past the last bound wrap back to New.
const MOON_PHASE_BOUNDS = [
  1.84566173161,  // New
  5.53698519483,  // Waxing Crescent
  9.22830865805,  // First Quarter
  12.91963212127, // Waxing Gibbous
  16.61095558449, // Full
  20.30227904771, // Waning Gibbous
  23.99360251093, // Last Quarter
  27.68492597415, // Waning Crescent
];

// Indexed by phase: New, Waxing Crescent, First Quarter, Waxing Gibbous, Full,
// Waning Gibbous, Last Quarter, Waning Crescent. The Southern Hemisphere sees
// the moon mirrored, so its set swaps the waxing/waning emoji.
const MOON_NORTH = ['🌑', '🌒', '🌓', '🌔', '🌕', '🌖', '🌗', '🌘'];
const MOON_SOUTH = ['🌑', '🌘', '🌗', '🌖', '🌕', '🌔', '🌓', '🌒'];

export function moonPhaseEmoji(unixTs: number, lat: number): string {
  const jd = (unixTs * 1000) / 86400000 + 2440587.5;
  let frac = (jd - 2451550.1) / LUNAR_MONTH;
  frac = frac - Math.floor(frac);
  if (frac < 0) frac += 1;
  const age = frac * LUNAR_MONTH;
  const emojis = lat < 0 ? MOON_SOUTH : MOON_NORTH;
  for (let i = 0; i < MOON_PHASE_BOUNDS.length; i++) {
    if (age < MOON_PHASE_BOUNDS[i]) return emojis[i];
  }
  return emojis[0];
}

// A sampled hour is night when its dt falls outside the sunrise–sunset window.
function isNightHour(d: HourlyResponse['data'][number]): boolean {
  return d.dt < d.sunrise || d.dt > d.sunset;
}

export function formatRange(values: number[], unit: string): string {
  const rounded = values.map(bankersRound);
  const lo = Math.min(...rounded);
  const hi = Math.max(...rounded);
  if (lo === hi) return `${lo}${unit}`;
  return `${lo} - ${hi}${unit}`;
}

export function formatLocalTime(unixTs: number, tzName: string): string {
  const date = new Date(unixTs * 1000);
  const parts = new Intl.DateTimeFormat('en-US', {
    hour: 'numeric',
    minute: '2-digit',
    hour12: true,
    timeZone: tzName,
  }).formatToParts(date);
  const hour = parts.find(p => p.type === 'hour')!.value;
  const minute = parts.find(p => p.type === 'minute')!.value;
  const dayPeriod = parts.find(p => p.type === 'dayPeriod')!.value.toLowerCase();
  return `${hour}:${minute}${dayPeriod}`;
}

function capitalize(s: string): string {
  if (!s) return s;
  const lower = s.toLowerCase();
  return lower[0].toUpperCase() + lower.slice(1);
}

// The weather block WITHOUT the SnowRaven attribution line. The standalone
// formatWeather appends ATTRIBUTION; the "Copy Weather and Tide Together" action
// uses the body so it can emit ONE combined attribution at the very bottom.
export function formatWeatherBody(responses: HourlyResponse[], tzName: string, lat: number): string {
  const first = responses[0].data[0];

  const temps = responses.map(r => r.data[0].temp);
  const humids = responses.map(r => r.data[0].humidity);
  const dews = responses.map(r => r.data[0].dew_point);
  const windSpeeds = responses.map(r => r.data[0].wind_speed);

  const windDescs = [...new Set(windSpeeds.map(windDescription))].sort(
    (a, b) => BEAUFORT_ORDER[a] - BEAUFORT_ORDER[b]
  );

  const seenDirs = new Set<string>();
  const windDirs: string[] = [];
  for (const r of responses) {
    const dir = cardinal(r.data[0].wind_deg);
    if (!seenDirs.has(dir)) {
      seenDirs.add(dir);
      windDirs.push(dir);
    }
  }

  const clouds = responses.map(r => r.data[0].clouds);
  const emoji = conditionEmoji(first.weather[0].id);
  const condition = capitalize(first.weather[0].description);
  const sunrise = formatLocalTime(first.sunrise, tzName);
  const sunset = formatLocalTime(first.sunset, tzName);

  // Night checklist (any sampled hour outside its sunrise–sunset window): append
  // the moon-phase emoji — computed from the checklist START hour, matching
  // SnowRaven — to the condition emoji, UNSPACED. Unspaced is the parity contract:
  // SnowRaven anchors a weather block on its last emoji RUN, so a space would split
  // the run.
  const moon = responses.some(r => isNightHour(r.data[0]))
    ? moonPhaseEmoji(first.dt, lat)
    : '';

  return [
    `${emoji}${moon}`,
    condition,
    `Temperature: ${formatRange(temps, '°F')}`,
    `Wind: ${windDescs.join(' - ')}`,
    `Wind Direction: ${windDirs.join(' - ')}`,
    `Cloud Cover: ${formatRange(clouds, '%')}`,
    `Humidity: ${formatRange(humids, '%')}`,
    `Dew point: ${formatRange(dews, '°F')}`,
    `Sunrise: ${sunrise}`,
    `Sunset: ${sunset}`,
  ].join('\n');
}

export function formatWeather(responses: HourlyResponse[], tzName: string, lat: number): string {
  return `${formatWeatherBody(responses, tzName, lat)}\n${ATTRIBUTION}`;
}
