// Golden parity test for formatWeather — the TypeScript port of
// weatherFormatter.golden.py. The expected strings are the EXACT output of the
// Python oracle (run `python3 weatherFormatter.golden.py`), encoded as .toBe so
// any byte drift (the U+2026/dash separators, the literal HTML <a> attribution,
// single-\n joins, no blank lines, no trailing newline) fails the build.
// FR-13..FR-19 / QA-19.

import { describe, it, expect } from 'vitest';
import {
  formatWeather, formatLocalTime, bankersRound, type HourlyResponse,
} from './weatherFormatter';

type Hour = HourlyResponse['data'][number];
const hr = (h: Hour): HourlyResponse => ({ data: [h] });

// Shared sunrise/sunset for the non-production fixtures (UTC timezone).
const SR = 1714494600; // -> 4:30pm UTC
const SS = 1714545000; // -> 6:30am UTC (next UTC day wrap)

const PRODUCTION = hr({
  temp: 54.3, humidity: 89, dew_point: 51.5, wind_speed: 8.3, wind_deg: 270,
  clouds: 100, weather: [{ id: 804, description: 'overcast clouds' }],
  sunrise: 1714554480, sunset: 1714603980,
});

const CALM = hr({
  temp: 72.0, humidity: 60, dew_point: 55.0, wind_speed: 0.5, wind_deg: 0,
  clouds: 20, weather: [{ id: 800, description: 'clear sky' }], sunrise: SR, sunset: SS,
});

const GALE = hr({
  temp: 45.0, humidity: 80, dew_point: 40.0, wind_speed: 45.0, wind_deg: 315,
  clouds: 90, weather: [{ id: 500, description: 'light rain' }], sunrise: SR, sunset: SS,
});

const GENTLE_A = hr({
  temp: 60.0, humidity: 70, dew_point: 50.0, wind_speed: 9.0, wind_deg: 90,
  clouds: 30, weather: [{ id: 801, description: 'few clouds' }], sunrise: SR, sunset: SS,
});

const GENTLE_B = hr({
  temp: 65.0, humidity: 65, dew_point: 48.0, wind_speed: 11.0, wind_deg: 180,
  clouds: 40, weather: [{ id: 801, description: 'few clouds' }], sunrise: SR, sunset: SS,
});

const FRESH_FIRST = hr({
  temp: 60.0, humidity: 70, dew_point: 50.0, wind_speed: 20.0, wind_deg: 90,
  clouds: 30, weather: [{ id: 801, description: 'few clouds' }], sunrise: SR, sunset: SS,
});

const LIGHT_SECOND = hr({
  temp: 65.0, humidity: 65, dew_point: 48.0, wind_speed: 5.0, wind_deg: 45,
  clouds: 40, weather: [{ id: 801, description: 'few clouds' }], sunrise: SR, sunset: SS,
});

const W_A = hr({
  temp: 70.0, humidity: 50, dew_point: 45.0, wind_speed: 8.0, wind_deg: 268,
  clouds: 0, weather: [{ id: 800, description: 'clear sky' }], sunrise: SR, sunset: SS,
});

const W_B = hr({
  temp: 72.0, humidity: 48, dew_point: 44.0, wind_speed: 10.0, wind_deg: 272,
  clouds: 5, weather: [{ id: 800, description: 'clear sky' }], sunrise: SR, sunset: SS,
});

const SW_FIRST = hr({
  temp: 68.0, humidity: 55, dew_point: 47.0, wind_speed: 8.0, wind_deg: 225,
  clouds: 10, weather: [{ id: 800, description: 'clear sky' }], sunrise: SR, sunset: SS,
});

const NE_SECOND = hr({
  temp: 70.0, humidity: 52, dew_point: 45.0, wind_speed: 9.0, wind_deg: 45,
  clouds: 15, weather: [{ id: 800, description: 'clear sky' }], sunrise: SR, sunset: SS,
});

const EQUAL = hr({
  temp: 72.0, humidity: 60, dew_point: 55.0, wind_speed: 8.0, wind_deg: 0,
  clouds: 50, weather: [{ id: 802, description: 'scattered clouds' }], sunrise: SR, sunset: SS,
});

const CAPS = hr({
  temp: 68.0, humidity: 55, dew_point: 47.0, wind_speed: 8.0, wind_deg: 90,
  clouds: 75, weather: [{ id: 803, description: 'BROKEN CLOUDS' }], sunrise: SR, sunset: SS,
});

describe('formatWeather golden parity (weatherFormatter.golden.py)', () => {
  it('production fixture (America/New_York) — FR-19', () => {
    expect(formatWeather([PRODUCTION], 'America/New_York')).toBe(
      '☁️\nOvercast clouds\nTemperature: 54°F\nWind: Gentle breeze\nWind Direction: W\nCloud Cover: 100%\nHumidity: 89%\nDew point: 52°F\nSunrise: 5:08am\nSunset: 6:53pm\nWeather generated by <a href="https://github.com/dtgibson/snowraven">SnowRaven</a>'
    );
  });

  it('calm wind single-hour (UTC)', () => {
    expect(formatWeather([CALM], 'UTC')).toBe(
      '☀️\nClear sky\nTemperature: 72°F\nWind: Calm\nWind Direction: N\nCloud Cover: 20%\nHumidity: 60%\nDew point: 55°F\nSunrise: 4:30pm\nSunset: 6:30am\nWeather generated by <a href="https://github.com/dtgibson/snowraven">SnowRaven</a>'
    );
  });

  it('gale wind single-hour (UTC)', () => {
    expect(formatWeather([GALE], 'UTC')).toBe(
      '🌧️\nLight rain\nTemperature: 45°F\nWind: Gale\nWind Direction: NW\nCloud Cover: 90%\nHumidity: 80%\nDew point: 40°F\nSunrise: 4:30pm\nSunset: 6:30am\nWeather generated by <a href="https://github.com/dtgibson/snowraven">SnowRaven</a>'
    );
  });

  it('multi-hour same beaufort (UTC)', () => {
    expect(formatWeather([GENTLE_A, GENTLE_B], 'UTC')).toBe(
      '🌤️\nFew clouds\nTemperature: 60 - 65°F\nWind: Gentle breeze\nWind Direction: E - S\nCloud Cover: 30 - 40%\nHumidity: 65 - 70%\nDew point: 48 - 50°F\nSunrise: 4:30pm\nSunset: 6:30am\nWeather generated by <a href="https://github.com/dtgibson/snowraven">SnowRaven</a>'
    );
  });

  it('multi-hour different beaufort sorted lightest-to-strongest (UTC)', () => {
    expect(formatWeather([FRESH_FIRST, LIGHT_SECOND], 'UTC')).toBe(
      '🌤️\nFew clouds\nTemperature: 60 - 65°F\nWind: Light breeze - Fresh breeze\nWind Direction: E - NE\nCloud Cover: 30 - 40%\nHumidity: 65 - 70%\nDew point: 48 - 50°F\nSunrise: 4:30pm\nSunset: 6:30am\nWeather generated by <a href="https://github.com/dtgibson/snowraven">SnowRaven</a>'
    );
  });

  it('multi-hour same direction dedup (UTC)', () => {
    expect(formatWeather([W_A, W_B], 'UTC')).toBe(
      '☀️\nClear sky\nTemperature: 70 - 72°F\nWind: Gentle breeze\nWind Direction: W\nCloud Cover: 0 - 5%\nHumidity: 48 - 50%\nDew point: 44 - 45°F\nSunrise: 4:30pm\nSunset: 6:30am\nWeather generated by <a href="https://github.com/dtgibson/snowraven">SnowRaven</a>'
    );
  });

  it('multi-hour different directions insertion order (UTC)', () => {
    expect(formatWeather([SW_FIRST, NE_SECOND], 'UTC')).toBe(
      '☀️\nClear sky\nTemperature: 68 - 70°F\nWind: Gentle breeze\nWind Direction: SW - NE\nCloud Cover: 10 - 15%\nHumidity: 52 - 55%\nDew point: 45 - 47°F\nSunrise: 4:30pm\nSunset: 6:30am\nWeather generated by <a href="https://github.com/dtgibson/snowraven">SnowRaven</a>'
    );
  });

  it('equal value range (UTC)', () => {
    expect(formatWeather([EQUAL, EQUAL], 'UTC')).toBe(
      '⛅\nScattered clouds\nTemperature: 72°F\nWind: Gentle breeze\nWind Direction: N\nCloud Cover: 50%\nHumidity: 60%\nDew point: 55°F\nSunrise: 4:30pm\nSunset: 6:30am\nWeather generated by <a href="https://github.com/dtgibson/snowraven">SnowRaven</a>'
    );
  });

  it('capitalize mixed case (UTC)', () => {
    expect(formatWeather([CAPS], 'UTC')).toBe(
      '🌥️\nBroken clouds\nTemperature: 68°F\nWind: Gentle breeze\nWind Direction: E\nCloud Cover: 75%\nHumidity: 55%\nDew point: 47°F\nSunrise: 4:30pm\nSunset: 6:30am\nWeather generated by <a href="https://github.com/dtgibson/snowraven">SnowRaven</a>'
    );
  });
});

describe('formatLocalTime golden (FR-18)', () => {
  it('noon -> 12:30pm (America/New_York)', () => {
    expect(formatLocalTime(1714494600, 'America/New_York')).toBe('12:30pm');
  });
  it('midnight -> 12:15am (America/New_York)', () => {
    expect(formatLocalTime(1714450500, 'America/New_York')).toBe('12:15am');
  });
});

describe('bankersRound golden (round-half-to-even, FR-14)', () => {
  it('matches Python round() at .5 boundaries', () => {
    expect(bankersRound(0.5)).toBe(0);
    expect(bankersRound(1.5)).toBe(2);
    expect(bankersRound(2.5)).toBe(2);
    expect(bankersRound(3.5)).toBe(4);
    expect(bankersRound(51.5)).toBe(52);
    expect(bankersRound(54.3)).toBe(54);
    expect(bankersRound(0.4)).toBe(0);
    expect(bankersRound(1.6)).toBe(2);
  });
});
